apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-bot-redis
  template:
    metadata:
      labels:
        app: trading-bot-redis
    spec:
      containers:
        - name: trading-bot-redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trading-bot-redis
  labels:
    app: trading-bot-redis
spec:
  type: NodePort
  selector:
    app: trading-bot-redis
  ports:
    - port: 6379
      nodePort: 30010